### ISSUE TITLE
Add Makilab in the agenda

### ISSUE THREAD

**Issue by jonadem** [Psycojoker/hackeragenda#108]
Hello,

I saw you agenda on the Hackerspace ML. Could you add Makilab's events to it ?

Is it formatted enough for you ?
http://makilab.org/events-list

Best regards,

Jonathan
Makilab's IT guy

**Comment by Psycojoker** [comment]
Hey :)

Actually it's already planned https://github.com/Psycojoker/hackeragenda/issues/66 right now I'm more in need of freetime (and energy) than anything else :p
 
Or if you are motivated you can even send me a patch, it's pretty easy to do: https://github.com/Psycojoker/hackeragenda/blob/master/agendas/be.py

Kind regards,

PS: I'm closing this ticket since there is already one for makilab
